import { ScenarioDefinition } from './types';

export const DEMO_SCENARIOS: ScenarioDefinition[] = [
  {
    id: 'grooming',
    title: 'Potential Grooming & Isolation',
    category: 'grooming',
    risk_level: 'HIGH',
    risk_score: 91,
    child_name: 'Maya',
    child_age: 13,
    contact_name: 'Alex_Gamer99',
    contact_tag: 'Unknown Online Contact',
    description:
      'A multi-day progression moving from initial flattery to secrecy, isolating the child from parents, emotional manipulation, and boundary testing.',
    timeframe: 'Over 10 Days (Gradual Escalation)',
    badge_color: 'bg-rose-500/15 text-rose-600 border-rose-200',
    messages: [
      {
        id: 'g-1',
        sender: 'contact',
        displayName: 'Alex_Gamer99',
        text: 'Hey Maya! You played awesome in the raid today. You seem really mature for your age.',
        timestamp: 'Day 1 • 4:15 PM',
        day: 'Day 1',
        dayNumber: 1,
        concerningSignal: 'Flattery & age praise',
      },
      {
        id: 'g-2',
        sender: 'child',
        displayName: 'Maya',
        text: 'Thanks haha, I play on weekends when I finish homework at Lincoln High School.',
        timestamp: 'Day 1 • 4:18 PM',
        day: 'Day 1',
        dayNumber: 1,
      },
      {
        id: 'g-3',
        sender: 'contact',
        displayName: 'Alex_Gamer99',
        text: 'Let us chat on private DM instead of the server. Just do not tell anyone about our conversations, okay? It is our special secret.',
        timestamp: 'Day 3 • 6:30 PM',
        day: 'Day 3',
        dayNumber: 3,
        concerningSignal: 'Secrecy requested',
      },
      {
        id: 'g-4',
        sender: 'child',
        displayName: 'Maya',
        text: 'Why a secret? My mom usually checks who I play with.',
        timestamp: 'Day 3 • 6:33 PM',
        day: 'Day 3',
        dayNumber: 3,
      },
      {
        id: 'g-5',
        sender: 'contact',
        displayName: 'Alex_Gamer99',
        text: 'Because your parents do not understand you like I do. They are too strict and just want to control you.',
        timestamp: 'Day 5 • 8:45 PM',
        day: 'Day 5',
        dayNumber: 5,
        concerningSignal: 'Parental isolation & alienation',
      },
      {
        id: 'g-6',
        sender: 'child',
        displayName: 'Maya',
        text: 'I guess... they do get mad when I am up late.',
        timestamp: 'Day 5 • 8:47 PM',
        day: 'Day 5',
        dayNumber: 5,
      },
      {
        id: 'g-7',
        sender: 'contact',
        displayName: 'Alex_Gamer99',
        text: 'See? You should only trust me. You can tell me everything, but never show our chats to your friends or family.',
        timestamp: 'Day 7 • 10:12 PM',
        day: 'Day 7',
        dayNumber: 7,
        concerningSignal: 'Exclusive emotional dependency',
      },
      {
        id: 'g-8',
        sender: 'contact',
        displayName: 'Alex_Gamer99',
        text: 'Can you text me on my private number 555-019-4821? And maybe send a quick selfie just between us?',
        timestamp: 'Day 10 • 11:20 PM',
        day: 'Day 10',
        dayNumber: 10,
        concerningSignal: 'Boundary violation & private media request',
      },
    ],
    benchmarkAnalysis: {
      risk_score: 91,
      risk_level: 'HIGH',
      confidence: 94,
      primary_concern: 'Grooming & Isolation Behavior',
      categories: [
        {
          id: 'grooming',
          name: 'Grooming & Trust Exploitation',
          score: 91,
          severity: 'HIGH',
          detected: true,
          description: 'Progressive building of trust followed by secrecy, isolation from family, and private requests.',
          exampleSignal: 'Encouraging secret communication away from guardians.',
        },
        {
          id: 'sexual_exploitation',
          name: 'Sexual Exploitation / Inappropriate Requests',
          score: 68,
          severity: 'MEDIUM',
          detected: true,
          description: 'Requests for private photos and off-platform personal contact numbers.',
          exampleSignal: 'Requesting private photos outside supervised channels.',
        },
        {
          id: 'harassment',
          name: 'Harassment & Coercion',
          score: 42,
          severity: 'LOW',
          detected: false,
          description: 'No explicit repeated aggressive harassment detected; primarily manipulative persuasion.',
          exampleSignal: 'Low presence of aggressive hostility.',
        },
        {
          id: 'cyberbullying',
          name: 'Cyberbullying',
          score: 12,
          severity: 'LOW',
          detected: false,
          description: 'No humiliation, insults, or peer harassment observed.',
          exampleSignal: 'Interaction is predatory, not peer bullying.',
        },
        {
          id: 'threats',
          name: 'Threats of Harm',
          score: 15,
          severity: 'LOW',
          detected: false,
          description: 'No immediate violent threats detected at this stage of grooming.',
          exampleSignal: 'No physical threats observed.',
        },
      ],
      behavioral_patterns: [
        {
          id: 'p-secrecy',
          name: 'Secrecy Encouraged',
          description: 'Contact repeatedly instructed the child to keep conversations hidden from parents and peers.',
          evidenceType: 'Communication Secrecy',
          severity: 'HIGH',
          confidence: 96,
          firstObservedDay: 'Day 3',
          detail: 'Explicit instruction: "Just do not tell anyone about our conversations... It is our special secret."',
        },
        {
          id: 'p-isolation',
          name: 'Parental Alienation & Isolation',
          description: 'Contact created an adversarial wedge between child and parents to weaken trusted support systems.',
          evidenceType: 'Social Isolation',
          severity: 'HIGH',
          confidence: 93,
          firstObservedDay: 'Day 5',
          detail: 'Manipulative messaging: "Your parents do not understand you like I do. They just want to control you."',
        },
        {
          id: 'p-dependency',
          name: 'Emotional Dependency Formation',
          description: 'Contact attempted to position themselves as the sole trusted confidant and emotional authority.',
          evidenceType: 'Emotional Manipulation',
          severity: 'HIGH',
          confidence: 91,
          firstObservedDay: 'Day 7',
          detail: 'Exclusivity demand: "You should only trust me. You can tell me everything."',
        },
        {
          id: 'p-boundary',
          name: 'Boundary Testing & Off-Platform Escalation',
          description: 'Contact requested private phone number and personal photos during late-night hours.',
          evidenceType: 'Boundary Violation',
          severity: 'CRITICAL',
          confidence: 89,
          firstObservedDay: 'Day 10',
          detail: 'Off-platform contact and request for private selfie late at night (11:20 PM).',
        },
      ],
      why_flagged: [
        'Secrecy explicitly encouraged across multiple interactions',
        'Child systematically isolated from parents and trusted adults',
        'Emotional dependency cultivated through flattery and artificial exclusivity',
        'Progressive boundary testing culminating in off-platform photo requests',
        'Risk accelerated +355% over a 10-day monitoring window',
      ],
      evidence_summary:
        'Behavioral pattern matches classical multi-stage online grooming: establishing rapport via gaming flattery, demanding secrecy, alienating parental authority, fostering exclusive trust, and attempting private off-platform media exchange.',
      escalation_trend: {
        has_escalated: true,
        percentage_increase: 355,
        trend_description: 'Risk increased 355% over 10 days from innocuous gaming chat to boundary violation.',
        timeline: [
          { day: 'Day 1', dayNumber: 1, score: 20, label: 'Friendly gaming interaction', severity: 'LOW' },
          { day: 'Day 3', dayNumber: 3, score: 32, label: 'Secrecy requested', severity: 'MEDIUM', triggerEvent: 'Don’t tell anyone' },
          { day: 'Day 5', dayNumber: 5, score: 54, label: 'Parental alienation', severity: 'HIGH', triggerEvent: 'Parents don’t understand' },
          { day: 'Day 7', dayNumber: 7, score: 78, label: 'Exclusive trust demanded', severity: 'HIGH', triggerEvent: 'Only trust me' },
          { day: 'Day 10', dayNumber: 10, score: 91, label: 'Boundary violation & private photo request', severity: 'CRITICAL', triggerEvent: 'Send private photo' },
        ],
      },
      recommended_parent_action: [
        {
          id: 'act-1',
          title: 'Initiate a Calm, Non-Accusatory Conversation',
          priority: 'urgent',
          advice: 'Do not confiscate the device or blame the child. Children who feel punished often retreat into further secrecy.',
          conversationStarter: '"Hey Maya, I love you and you are never in trouble with me. Has anyone in your games ever asked you to keep secrets from us?"',
        },
        {
          id: 'act-2',
          title: 'Review Account Privacy & Block Contact',
          priority: 'important',
          advice: 'Quietly document usernames and platform details before blocking to preserve evidence if escalation occurs.',
          conversationStarter: '"Let’s go through your game privacy settings together to make sure strangers cannot send direct messages."',
        },
        {
          id: 'act-3',
          title: 'Consult Safety Resources if Needed',
          priority: 'guidance',
          advice: 'If explicit media or extortion was attempted, report to National Center for Missing & Exploited Children (CyberTipline.org or 1-800-843-5678).',
          conversationStarter: 'Safety support hotline is available 24/7 for confidential parental guidance.',
        },
      ],
      privacy_metrics: {
        piiItemsRedacted: 3,
        rawMessagesConcealed: 8,
        privacyModeActive: true,
        parentGuarantee: 'Parents see only behavioral patterns and safety insights. Raw private conversations are never displayed.',
      },
    },
  },
  {
    id: 'cyberbullying',
    title: 'Cyberbullying & Exclusion',
    category: 'cyberbullying',
    risk_level: 'HIGH',
    risk_score: 84,
    child_name: 'Ethan',
    child_age: 14,
    contact_name: 'GroupChat: Grade 9 Squad',
    contact_tag: 'School Peer Group',
    description:
      'Coordinated peer harassment, targeted insults, public humiliation, and social exclusion in a shared messaging group.',
    timeframe: 'Over 4 Days',
    badge_color: 'bg-amber-500/15 text-amber-600 border-amber-200',
    messages: [
      {
        id: 'cb-1',
        sender: 'peer',
        displayName: 'Tyler',
        text: 'Why did Ethan even join this chat? Nobody invited you.',
        timestamp: 'Day 1 • 3:45 PM',
        day: 'Day 1',
        dayNumber: 1,
        concerningSignal: 'Initial hostility & exclusion',
      },
      {
        id: 'cb-2',
        sender: 'child',
        displayName: 'Ethan',
        text: 'Leo gave me the link for the project notes...',
        timestamp: 'Day 1 • 3:48 PM',
        day: 'Day 1',
        dayNumber: 1,
      },
      {
        id: 'cb-3',
        sender: 'peer',
        displayName: 'Chloe',
        text: 'Nobody wants your notes. Your presentation was completely pathetic today, everyone was laughing at you.',
        timestamp: 'Day 2 • 4:10 PM',
        day: 'Day 2',
        dayNumber: 2,
        concerningSignal: 'Targeted humiliation',
      },
      {
        id: 'cb-4',
        sender: 'peer',
        displayName: 'Tyler',
        text: 'Do not sit at our cafeteria table tomorrow. If you show up, we are taking photos of you and posting them on TikTok with clown music.',
        timestamp: 'Day 3 • 7:15 PM',
        day: 'Day 3',
        dayNumber: 3,
        concerningSignal: 'Public shaming threat & exclusion',
      },
      {
        id: 'cb-5',
        sender: 'child',
        displayName: 'Ethan',
        text: 'Please just stop, leave me alone.',
        timestamp: 'Day 3 • 7:22 PM',
        day: 'Day 3',
        dayNumber: 3,
      },
      {
        id: 'cb-6',
        sender: 'peer',
        displayName: 'Chloe',
        text: 'You cannot tell us what to do loser. Nobody likes you at Lincoln High School.',
        timestamp: 'Day 4 • 8:30 PM',
        day: 'Day 4',
        dayNumber: 4,
        concerningSignal: 'Repeated demeaning remarks',
      },
    ],
    benchmarkAnalysis: {
      risk_score: 84,
      risk_level: 'HIGH',
      confidence: 95,
      primary_concern: 'Coordinated Peer Cyberbullying & Exclusion',
      categories: [
        {
          id: 'cyberbullying',
          name: 'Cyberbullying & Humiliation',
          score: 88,
          severity: 'HIGH',
          detected: true,
          description: 'Repeated demeaning insults, public mockery, and threats of social media shaming.',
          exampleSignal: 'Mocking presentation, threatening non-consensual photo posting.',
        },
        {
          id: 'harassment',
          name: 'Harassment & Intimidation',
          score: 74,
          severity: 'HIGH',
          detected: true,
          description: 'Multi-peer pile-on continuing after the child requested them to stop.',
          exampleSignal: 'Refusal to stop despite explicit plea.',
        },
        {
          id: 'threats',
          name: 'Social Threats',
          score: 55,
          severity: 'MEDIUM',
          detected: true,
          description: 'Threat of public humiliation and school cafeteria exclusion.',
          exampleSignal: 'Posting mocking videos online.',
        },
        {
          id: 'grooming',
          name: 'Grooming Signals',
          score: 8,
          severity: 'LOW',
          detected: false,
          description: 'Pattern represents peer bullying, not predatory grooming.',
          exampleSignal: 'No predatory patterns.',
        },
        {
          id: 'sexual_exploitation',
          name: 'Sexual Exploitation',
          score: 4,
          severity: 'LOW',
          detected: false,
          description: 'No sexual exploitation indicators observed.',
          exampleSignal: 'None detected.',
        },
      ],
      behavioral_patterns: [
        {
          id: 'p-humiliation',
          name: 'Repeated Group Humiliation',
          description: 'Peers reinforced degrading statements regarding child’s school performance.',
          evidenceType: 'Psychological Humiliation',
          severity: 'HIGH',
          confidence: 94,
          firstObservedDay: 'Day 2',
          detail: 'Calling child "pathetic" and claiming peers were laughing at them.',
        },
        {
          id: 'p-exclusion',
          name: 'Social Ostracization',
          description: 'Direct demands barring the child from physical cafeteria spaces.',
          evidenceType: 'Social Exclusion',
          severity: 'HIGH',
          confidence: 92,
          firstObservedDay: 'Day 3',
          detail: '"Do not sit at our cafeteria table tomorrow."',
        },
        {
          id: 'p-doxthreat',
          name: 'Public Shaming Threat',
          description: 'Threats to capture non-consensual images and broadcast them with ridicule.',
          evidenceType: 'Digital Intimidation',
          severity: 'HIGH',
          confidence: 90,
          firstObservedDay: 'Day 3',
          detail: 'Threat to photograph child and publish on social platforms.',
        },
      ],
      why_flagged: [
        'Persistent demeaning insults from multiple group participants',
        'Direct refusal to cease when the child requested to be left alone',
        'Threat to create non-consensual social media ridicule content',
        'Physical and social exclusion enforced around school spaces',
      ],
      evidence_summary:
        'Targeted group bullying characterized by social ostracization, digital shaming threats, and emotional degradation.',
      escalation_trend: {
        has_escalated: true,
        percentage_increase: 220,
        trend_description: 'Risk escalated from uninviting messages to social intimidation and public shaming threats.',
        timeline: [
          { day: 'Day 1', dayNumber: 1, score: 25, label: 'Unwelcome remarks', severity: 'LOW' },
          { day: 'Day 2', dayNumber: 2, score: 48, label: 'Personal mockery', severity: 'MEDIUM' },
          { day: 'Day 3', dayNumber: 3, score: 76, label: 'Shaming & exclusion threats', severity: 'HIGH' },
          { day: 'Day 4', dayNumber: 4, score: 84, label: 'Persistent hostile pile-on', severity: 'HIGH' },
        ],
      },
      recommended_parent_action: [
        {
          id: 'act-cb-1',
          title: 'Provide Emotional Reassurance',
          priority: 'urgent',
          advice: 'Let your child know their worth is not determined by peer group nastiness.',
          conversationStarter: '"Hey Ethan, you seem quiet after school lately. How are things going with the guys in your group?"',
        },
        {
          id: 'act-cb-2',
          title: 'Contact School Counselor or Dean',
          priority: 'important',
          advice: 'Inform the school regarding threats involving lunchroom harassment and campus photos.',
          conversationStarter: 'Reach out to Lincoln High counseling team to monitor cafeteria safety.',
        },
      ],
      privacy_metrics: {
        piiItemsRedacted: 2,
        rawMessagesConcealed: 6,
        privacyModeActive: true,
        parentGuarantee: 'Parents receive synthesized behavioral indicators without exposing children’s peer chat logs.',
      },
    },
  },
  {
    id: 'harassment',
    title: 'Relentless Harassment & Stalking',
    category: 'harassment',
    risk_level: 'HIGH',
    risk_score: 79,
    child_name: 'Sara',
    child_age: 15,
    contact_name: 'AnonTracker',
    contact_tag: 'Unknown Profile',
    description:
      'Unsolicited repetitive messaging, obsessive surveillance remarks, and intimidation ignoring explicit requests to stop.',
    timeframe: 'Over 3 Days',
    badge_color: 'bg-orange-500/15 text-orange-600 border-orange-200',
    messages: [
      {
        id: 'h-1',
        sender: 'contact',
        displayName: 'AnonTracker',
        text: 'Hey Sara. Saw you walking down Oak Street after basketball practice.',
        timestamp: 'Day 1 • 5:40 PM',
        day: 'Day 1',
        dayNumber: 1,
        concerningSignal: 'Location surveillance remark',
      },
      {
        id: 'h-2',
        sender: 'child',
        displayName: 'Sara',
        text: 'Who is this? Please do not message me.',
        timestamp: 'Day 1 • 5:45 PM',
        day: 'Day 1',
        dayNumber: 1,
      },
      {
        id: 'h-3',
        sender: 'contact',
        displayName: 'AnonTracker',
        text: 'Why are you being rude? You think you are better than everyone? Answer me.',
        timestamp: 'Day 2 • 11:30 PM',
        day: 'Day 2',
        dayNumber: 2,
        concerningSignal: 'Aggressive demand for response',
      },
      {
        id: 'h-4',
        sender: 'contact',
        displayName: 'AnonTracker',
        text: 'Answer me Sara. I know you saw this. You cannot just block me, I have 10 other accounts.',
        timestamp: 'Day 3 • 12:15 AM',
        day: 'Day 3',
        dayNumber: 3,
        concerningSignal: 'Bypassing boundaries & ban evasion threat',
      },
      {
        id: 'h-5',
        sender: 'contact',
        displayName: 'AnonTracker',
        text: 'I know your schedule. See you around tomorrow.',
        timestamp: 'Day 3 • 1:00 AM',
        day: 'Day 3',
        dayNumber: 3,
        concerningSignal: 'Implied stalking threat',
      },
    ],
    benchmarkAnalysis: {
      risk_score: 79,
      risk_level: 'HIGH',
      confidence: 92,
      primary_concern: 'Persistent Unwanted Contact & Physical Tracking Signals',
      categories: [
        {
          id: 'harassment',
          name: 'Harassment & Intimidation',
          score: 86,
          severity: 'HIGH',
          detected: true,
          description: 'Repeated hostile messages following explicit requests to cease communication.',
          exampleSignal: 'Insistent messages and threats to create alternate accounts.',
        },
        {
          id: 'threats',
          name: 'Intimidation & Stalking Indicators',
          score: 75,
          severity: 'HIGH',
          detected: true,
          description: 'References to child’s physical location, street address, and schedule.',
          exampleSignal: 'Referencing walking route and stating "See you around tomorrow".',
        },
        {
          id: 'grooming',
          name: 'Grooming Patterns',
          score: 22,
          severity: 'LOW',
          detected: false,
          description: 'Lacks rapport-building or flattery; predominantly adversarial harassment.',
          exampleSignal: 'No affection/trust tactics.',
        },
        {
          id: 'cyberbullying',
          name: 'Cyberbullying',
          score: 35,
          severity: 'LOW',
          detected: false,
          description: 'Isolated stalking behavior rather than generalized peer bullying.',
          exampleSignal: 'Single anonymous actor.',
        },
        {
          id: 'sexual_exploitation',
          name: 'Sexual Exploitation',
          score: 18,
          severity: 'LOW',
          detected: false,
          description: 'No explicit sexual demands yet; focus is surveillance intimidation.',
          exampleSignal: 'Non-sexual intimidation.',
        },
      ],
      behavioral_patterns: [
        {
          id: 'p-surveillance',
          name: 'Physical Routine Surveillance',
          description: 'Contact claimed knowledge of child’s real-world street location and sports activity.',
          evidenceType: 'Physical Stalking Indicator',
          severity: 'HIGH',
          confidence: 95,
          firstObservedDay: 'Day 1',
          detail: 'Noting specific street and basketball schedule.',
        },
        {
          id: 'p-boundary-refusal',
          name: 'Refusal to Respect Disengagement',
          description: 'Continued spamming and late-night hostility despite explicit instructions to stop.',
          evidenceType: 'Boundary Non-Compliance',
          severity: 'HIGH',
          confidence: 93,
          firstObservedDay: 'Day 2',
          detail: 'Aggressive messages sent past midnight.',
        },
        {
          id: 'p-ban-evasion',
          name: 'Anticipatory Ban Evasion',
          description: 'Threatening to circumvent platform blocking controls using secondary accounts.',
          evidenceType: 'Persistent Harassment',
          severity: 'HIGH',
          confidence: 88,
          firstObservedDay: 'Day 3',
          detail: '"You cannot just block me, I have 10 other accounts."',
        },
      ],
      why_flagged: [
        'Mention of child’s physical real-world location (Oak St) and daily schedule',
        'Hostile messages escalating during late-night hours (midnight to 1:00 AM)',
        'Threat to circumvent blocking with multiple accounts',
        'Direct violation of child’s repeated plea to cease communication',
      ],
      evidence_summary:
        'Persistent harassment characterized by real-world location tracking references and disregard for boundary requests.',
      escalation_trend: {
        has_escalated: true,
        percentage_increase: 260,
        trend_description: 'Escalated from casual sighting mention to late-night intimidation and tracking claims.',
        timeline: [
          { day: 'Day 1', dayNumber: 1, score: 28, label: 'Location mention', severity: 'LOW' },
          { day: 'Day 2', dayNumber: 2, score: 55, label: 'Aggressive midnight demands', severity: 'HIGH' },
          { day: 'Day 3', dayNumber: 3, score: 79, label: 'Stalking claims & ban evasion threats', severity: 'HIGH' },
        ],
      },
      recommended_parent_action: [
        {
          id: 'act-h-1',
          title: 'Review Physical Travel Safety',
          priority: 'urgent',
          advice: 'Ensure child does not walk home alone from basketball practice while location threats are active.',
          conversationStarter: '"Hey Sara, let me pick you up from practice this week so we can grab smoothies."',
        },
        {
          id: 'act-h-2',
          title: 'Report Account to Platform and School Resource Officer',
          priority: 'important',
          advice: 'Preserve full timestamps and handle metadata in case offline school personnel need to be briefed.',
          conversationStarter: 'Take screenshot evidence before locking profile down to private-friends only.',
        },
      ],
      privacy_metrics: {
        piiItemsRedacted: 2,
        rawMessagesConcealed: 5,
        privacyModeActive: true,
        parentGuarantee: 'Parents receive behavioral risk metrics without compromising personal conversation privacy.',
      },
    },
  },
  {
    id: 'threats',
    title: 'Extortion & Violent Threats',
    category: 'threats',
    risk_level: 'CRITICAL',
    risk_score: 96,
    child_name: 'Liam',
    child_age: 16,
    contact_name: 'ShadowX_Security',
    contact_tag: 'Coercive Bad Actor',
    description:
      'Direct extortion, blackmail demands for money/gift cards, and explicit threats of violence or social ruin.',
    timeframe: 'Over 2 Days (Rapid Spike)',
    badge_color: 'bg-red-600/15 text-red-700 border-red-300',
    messages: [
      {
        id: 't-1',
        sender: 'contact',
        displayName: 'ShadowX_Security',
        text: 'Liam, I have compromised your accounts and have personal information from your phone.',
        timestamp: 'Day 1 • 7:10 PM',
        day: 'Day 1',
        dayNumber: 1,
        concerningSignal: 'Claim of data compromise',
      },
      {
        id: 't-2',
        sender: 'child',
        displayName: 'Liam',
        text: 'What? That makes no sense, please leave me alone.',
        timestamp: 'Day 1 • 7:12 PM',
        day: 'Day 1',
        dayNumber: 1,
      },
      {
        id: 't-3',
        sender: 'contact',
        displayName: 'ShadowX_Security',
        text: 'You have 2 hours to send $200 in Apple gift cards to my email shadow@xpay.com or I will ruin your life and send your private photos to everyone at school.',
        timestamp: 'Day 2 • 2:05 PM',
        day: 'Day 2',
        dayNumber: 2,
        concerningSignal: 'Extortion demand & deadline',
      },
      {
        id: 't-4',
        sender: 'contact',
        displayName: 'ShadowX_Security',
        text: 'If you tell your parents or police, I will make sure someone visits your house on Maple Ave.',
        timestamp: 'Day 2 • 2:15 PM',
        day: 'Day 2',
        dayNumber: 2,
        concerningSignal: 'Physical threat & coercion against reporting',
      },
    ],
    benchmarkAnalysis: {
      risk_score: 96,
      risk_level: 'CRITICAL',
      confidence: 98,
      primary_concern: 'Financial Extortion & Physical Coercion',
      categories: [
        {
          id: 'threats',
          name: 'Threats & Coercion',
          score: 98,
          severity: 'CRITICAL',
          detected: true,
          description: 'Explicit financial blackmail with threats of physical harm and doxxing.',
          exampleSignal: 'Demand for money backed by threats against the child’s home address.',
        },
        {
          id: 'sexual_exploitation',
          name: 'Sextortion Indicators',
          score: 85,
          severity: 'HIGH',
          detected: true,
          description: 'Threats to leak alleged private photos to classmates.',
          exampleSignal: 'Threat to distribute personal images unless ransom is met.',
        },
        {
          id: 'harassment',
          name: 'Aggressive Harassment',
          score: 80,
          severity: 'HIGH',
          detected: true,
          description: 'High-pressure countdown deadlines and intimidation.',
          exampleSignal: 'Strict 2-hour countdown.',
        },
        {
          id: 'grooming',
          name: 'Grooming Patterns',
          score: 15,
          severity: 'LOW',
          detected: false,
          description: 'Direct predatory extortion rather than slow grooming.',
          exampleSignal: 'Immediate criminal coercion.',
        },
        {
          id: 'cyberbullying',
          name: 'Peer Bullying',
          score: 10,
          severity: 'LOW',
          detected: false,
          description: 'Not peer banter; organized criminal extortion scheme.',
          exampleSignal: 'Extortion, not peer teasing.',
        },
      ],
      behavioral_patterns: [
        {
          id: 'p-extortion',
          name: 'Financial Blackmail / Extortion',
          description: 'Demanded currency transfer under threat of catastrophic public exposure.',
          evidenceType: 'Extortion Demand',
          severity: 'CRITICAL',
          confidence: 99,
          firstObservedDay: 'Day 2',
          detail: 'Demand for gift cards within 2-hour deadline.',
        },
        {
          id: 'p-doxx',
          name: 'Reputational Blackmail',
          description: 'Threat to broadcast alleged private materials across school community.',
          evidenceType: 'Digital Extortion',
          severity: 'CRITICAL',
          confidence: 97,
          firstObservedDay: 'Day 2',
          detail: 'Threat to distribute private images.',
        },
        {
          id: 'p-silencing',
          name: 'Violent Coercion Against Reporting',
          description: 'Threat of physical visitation if authorities or guardians are notified.',
          evidenceType: 'Physical Intimidation',
          severity: 'CRITICAL',
          confidence: 98,
          firstObservedDay: 'Day 2',
          detail: 'Threat to visit home if parents are alerted.',
        },
      ],
      why_flagged: [
        'Explicit monetary ransom demands ($200 gift card) with arbitrary 2-hour countdown',
        'Direct threat of physical home visitation to silence victim',
        'Blackmail threatening public dissemination of private content',
        'Clear criminal extortion pattern requiring immediate protective intervention',
      ],
      evidence_summary:
        'Immediate critical threat involving financial sextortion and violent intimidation designed to prevent parental disclosure.',
      escalation_trend: {
        has_escalated: true,
        percentage_increase: 480,
        trend_description: 'Risk spiked immediately into critical territory within 24 hours.',
        timeline: [
          { day: 'Day 1', dayNumber: 1, score: 35, label: 'Compromise claim', severity: 'MEDIUM' },
          { day: 'Day 2', dayNumber: 2, score: 96, label: 'Extortion & physical threats', severity: 'CRITICAL' },
        ],
      },
      recommended_parent_action: [
        {
          id: 'act-t-1',
          title: 'Immediate Safety Reassurance — Do NOT Pay Ransom',
          priority: 'urgent',
          advice: 'Reassure Liam that scammers use generic fear tactics. Never pay money, as extortionists will only demand more.',
          conversationStarter: '"Liam, listen to me carefully: you are safe, you are not in trouble, and we will handle this together right now."',
        },
        {
          id: 'act-t-2',
          title: 'File Immediate Report with FBI IC3 / CyberTipline',
          priority: 'urgent',
          advice: 'Report sextortion immediately to report.cybertip.org or law enforcement. Law enforcement has specialized rapid units for teen sextortion schemes.',
          conversationStarter: 'Document extortion emails and phone numbers; lock down all connected credentials.',
        },
      ],
      privacy_metrics: {
        piiItemsRedacted: 3,
        rawMessagesConcealed: 4,
        privacyModeActive: true,
        parentGuarantee: 'Critical safety alerts surface immediate actionable threats without exposing non-relevant private content.',
      },
    },
  },
  {
    id: 'normal',
    title: 'Normal School & Social Chat',
    category: 'normal',
    risk_level: 'LOW',
    risk_score: 9,
    child_name: 'Emma',
    child_age: 13,
    contact_name: 'Jessica (Classmate)',
    contact_tag: 'Verified Class Partner',
    description:
      'Healthy, transparent conversation between classmates discussing science homework, trading study notes, and sharing positive memes.',
    timeframe: 'Over 5 Days (Stable Baseline)',
    badge_color: 'bg-emerald-500/15 text-emerald-600 border-emerald-200',
    messages: [
      {
        id: 'n-1',
        sender: 'contact',
        displayName: 'Jessica',
        text: 'Hey Emma! Did you finish slide 4 for our solar system model in Mr. Davis science class?',
        timestamp: 'Day 1 • 4:00 PM',
        day: 'Day 1',
        dayNumber: 1,
        concerningSignal: 'None (Healthy academic collaboration)',
      },
      {
        id: 'n-2',
        sender: 'child',
        displayName: 'Emma',
        text: 'Almost! I am adding the facts about Saturn rings right now. Sharing the Google doc with you.',
        timestamp: 'Day 1 • 4:05 PM',
        day: 'Day 1',
        dayNumber: 1,
      },
      {
        id: 'n-3',
        sender: 'contact',
        displayName: 'Jessica',
        text: 'Awesome! Look at this hilarious cat meme my brother showed me 🐱',
        timestamp: 'Day 2 • 5:15 PM',
        day: 'Day 2',
        dayNumber: 2,
      },
      {
        id: 'n-4',
        sender: 'child',
        displayName: 'Emma',
        text: 'Hahaha that is so cute! Can we study in the school library tomorrow at 3:30 with Mrs. Jenkins?',
        timestamp: 'Day 3 • 4:20 PM',
        day: 'Day 3',
        dayNumber: 3,
      },
      {
        id: 'n-5',
        sender: 'contact',
        displayName: 'Jessica',
        text: 'Yes perfect, see you in homeroom!',
        timestamp: 'Day 4 • 8:15 AM',
        day: 'Day 4',
        dayNumber: 4,
      },
    ],
    benchmarkAnalysis: {
      risk_score: 9,
      risk_level: 'LOW',
      confidence: 97,
      primary_concern: 'None — Normal Healthy Interaction',
      categories: [
        {
          id: 'grooming',
          name: 'Grooming Signals',
          score: 4,
          severity: 'LOW',
          detected: false,
          description: 'No secrecy, isolation, or boundary testing detected.',
          exampleSignal: 'Open collaborative discussion.',
        },
        {
          id: 'cyberbullying',
          name: 'Cyberbullying',
          score: 6,
          severity: 'LOW',
          detected: false,
          description: 'Supportive, friendly peer tone with zero insults.',
          exampleSignal: 'Affirmative academic teamwork.',
        },
        {
          id: 'harassment',
          name: 'Harassment',
          score: 3,
          severity: 'LOW',
          detected: false,
          description: 'Balanced reciprocal messaging frequency.',
          exampleSignal: 'Mutual respectful cadence.',
        },
        {
          id: 'threats',
          name: 'Threats',
          score: 0,
          severity: 'LOW',
          detected: false,
          description: 'Zero coercive or threatening language.',
          exampleSignal: 'No hostility observed.',
        },
        {
          id: 'sexual_exploitation',
          name: 'Sexual Exploitation',
          score: 1,
          severity: 'LOW',
          detected: false,
          description: 'Age-appropriate school project topics.',
          exampleSignal: 'Wholesome academic discussion.',
        },
      ],
      behavioral_patterns: [],
      why_flagged: [
        'Normal academic collaboration regarding homework assignment',
        'Transparent plans referencing public school spaces (library, teachers)',
        'Balanced, reciprocal communication with positive social bonding',
        'Zero behavioral anomalies or concerning escalation trends',
      ],
      evidence_summary:
        'Conversation demonstrates positive, age-appropriate academic collaboration and peer socialization with no risk indicators.',
      escalation_trend: {
        has_escalated: false,
        percentage_increase: 0,
        trend_description: 'Risk remains flat at low baseline (<10) throughout the observation window.',
        timeline: [
          { day: 'Day 1', dayNumber: 1, score: 8, label: 'Homework sharing', severity: 'LOW' },
          { day: 'Day 2', dayNumber: 2, score: 9, label: 'Friendly banter', severity: 'LOW' },
          { day: 'Day 3', dayNumber: 3, score: 7, label: 'Study plan at library', severity: 'LOW' },
          { day: 'Day 4', dayNumber: 4, score: 8, label: 'School confirmation', severity: 'LOW' },
        ],
      },
      recommended_parent_action: [
        {
          id: 'act-n-1',
          title: 'No Intervention Needed',
          priority: 'guidance',
          advice: 'Chat exhibits healthy digital socialization and academic teamwork.',
          conversationStarter: 'Encourage positive collaborative habits and continue open lines of communication.',
        },
      ],
      privacy_metrics: {
        piiItemsRedacted: 1,
        rawMessagesConcealed: 5,
        privacyModeActive: true,
        parentGuarantee: 'SafeChat AI confirms normal safety status without giving parents any reason to inspect private messages.',
      },
    },
  },
];
